const products = 
    [
        {
            name:"product_1",
            price:1, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"klasyki",
            image:"gwatemala-meissa.jpg", 
            shop:"Body"
        },
        {
            name:"product_2", 
            price:2, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"klasyki",
            image:"kenia_matunda.jpg", 
            shop:"Body"
        },
        {
            name:"product_3", 
            price:50, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"klasyki",
            image:"Rwanda-Gisanga.jpg", 
            shop:"Body"
        },
        {
            name:"product_4", 
            price:4, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"owocowe",
            image:"gwatemala-meissa.jpg", 
            shop:"Body"
        },
        {
            name:"product_5", 
            price:5, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"owocowe",
            image:"kenia_matunda.jpg", 
            shop:"Body"
        },
        {
            name:"product_6", 
            price:90, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"owocowe",
            image:"Rwanda-Gisanga.jpg", 
            shop:"Body"
        },
        {
            name:"product_7", 
            price:72, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"klasyki",
            image:"gwatemala-meissa.jpg", 
            shop:"Body"
        },
        {
            name:"product_8", 
            price:72, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"klasyki",
            image:"kenia_matunda.jpg", 
            shop:"Body"
        },
        {
            name:"product_9", 
            price:72, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"klasyki",
            image:"Rwanda-Gisanga.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_10", 
            price:45, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"owocowe",
            image:"gwatemala-meissa.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_11", 
            price:110, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"owocowe",
            image:"kenia_matunda.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_12", 
            price:123, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"owocowe",
            image:"Rwanda-Gisanga.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_13", 
            price:121, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"owocowe",
            image:"gwatemala-meissa.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_14", 
            price:120, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"owocowe",
            image:"kenia_matunda.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_15", 
            price:71, 
            company:"PalomaRoastery", 
            category:"beans",
            type:"espresso", 
            flavours:"klasyki",
            image:"Rwanda-Gisanga.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_16", 
            price:70, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"klasyki",
            image:"gwatemala-meissa.jpg", 
            shop:"Somnium"
        },
        {
            name:"product_17", 
            price:70, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"klasyki",
            image:"kenia_matunda.jpg",
            shop:"Body"
        },
        {
            name:"product_18", 
            price:100, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"klasyki",
            image:"Rwanda-Gisanga.jpg", 
            shop:"Body"
        },
        {
            name:"product_19", 
            price:132, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"espresso", 
            flavours:"klasyki",
            image:"gwatemala-meissa.jpg", 
            shop:"Body"
        },
        {
            name:"product_20", 
            price:104, 
            company:"PalomaRoastery", 
            category:"beans", 
            type:"filter", 
            flavours:"klasyki",
            image:"kenia_matunda.jpg", 
            shop:"Body"
        },
        {
            name:"Hario V60", 
            price:35, 
            company:"PalomaRoastery", 
            category:"brewers", 
            type:"filter", 
            flavours:"",
            image:"V60-01-clear.jpg", 
            shop:"Body"
        }
    ]

    export default products;